services:
  - type: web
    name: androtrack
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Qn3bSiPusT5nTAUqLIQimWTFefcurEL88wOHEfKpI8I=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://androtrack.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
